site_name: Kairos
repo_url: https://github.com/sashayerty/kairos
repo_name: sashayerty/kairos
nav:
  - Главная: README.md
  - Начало: getting_started.md
  - "Локальный запуск": local_setup.md
  - "Настройки конфигурации": config_settings.md
  - "Переменные .env": dotenv_variables.md
  - "RestAPI Docs": restapi.md
  - "Структура проекта": structure.md
  - "API проекта": api.md
  - "Примеры UI": ui_examples.md
theme:
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  language: ru
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: green
      accent: green
      toggle:
        icon: material/link
        name: Переключить на светлую тему

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Переключить на темную тему

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Переключить на системную тему
# plugins:
#   - offline
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences
